// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ApplyUpdate(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['ApplyUpdate'](arg1, arg2, arg3, arg4, arg5);
}

export function GetCategories() {
  return window['go']['main']['App']['GetCategories']();
}

export function GetImageBase64(arg1) {
  return window['go']['main']['App']['GetImageBase64'](arg1);
}

export function GetRepoIndex() {
  return window['go']['main']['App']['GetRepoIndex']();
}

export function LoadController(arg1) {
  return window['go']['main']['App']['LoadController'](arg1);
}

export function SelectRepoRoot() {
  return window['go']['main']['App']['SelectRepoRoot']();
}

export function SelectZip() {
  return window['go']['main']['App']['SelectZip']();
}
