// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';
import {utils} from '../models';

export function ApplyUpdate():Promise<void>;

export function GetImageBase64(arg1:string):Promise<string>;

export function GetRepoIndex():Promise<Array<models.IndexEntry>>;

export function SelectRepoRoot():Promise<string>;

export function SelectZip():Promise<utils.ParsedPackage>;
