// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ApplyUpdate() {
  return window['go']['main']['App']['ApplyUpdate']();
}

export function GetImageBase64(arg1) {
  return window['go']['main']['App']['GetImageBase64'](arg1);
}

export function GetRepoIndex() {
  return window['go']['main']['App']['GetRepoIndex']();
}

export function SelectRepoRoot() {
  return window['go']['main']['App']['SelectRepoRoot']();
}

export function SelectZip() {
  return window['go']['main']['App']['SelectZip']();
}
